export const emotionConfig = {
  confusion: {
    colorHex: "#4d5251",
    colorName: "Light Gray",
    emoji: "/images/confusion.jpeg",
    borderHex: "#faf4ed",
    textHex: "#ccc0a7",
  },
  disappointment: {
    colorHex: "#2c3b42",
    colorName: "Dull Grayish-Blue",
    emoji: "/images/disappointed.jpeg",
    borderHex: "#7eb5fc",
    textHex: "#819cb5",
  },
  neutral: {
    colorHex: "#665a2c",
    colorName: "Beige",
    emoji: "/images/neutral.jpeg",
    borderHex: "#f7c692",
    textHex: "#fcb72b",
  },
  nervousness: {
    colorHex: "#b4b87b",
    colorName: "Light Yellow",
    emoji: "/images/nervous.jpeg",
    borderHex: "#f7e797",
    textHex: "#b4b87b",
  },
  realization: {
    colorHex: "#b3b870",
    colorName: "Light Bulb Yellow",
    emoji: "/images/realised.jpeg",
    borderHex: "#fbfcca",
    textHex: "#b3b870",
  },
  sadness: {
    colorHex: "#30365e",
    colorName: "Cool Blue",
    emoji: "/images/sad.jpeg",
    borderHex: "#738efa",
    textHex: "#749ffc",
  },
  disapproval: {
    colorHex: "#405735",
    colorName: "Muted Olive",
    emoji: "/images/disapproval.jpeg",
    borderHex: "#1f5e26",
    textHex: "#405735",
  },
  annoyance: {
    colorHex: "#d46d24",
    colorName: "Irritating Orange",
    emoji: "/images/annoyed.jpeg",
    borderHex: "#633606",
    textHex: "#d46d24",
  },
  approval: {
    colorHex: "#86ad66",
    colorName: "Green Light",
    emoji: "/images/approve.jpeg",
    borderHex: "#522e08",
    textHex: "#86ad66",
  },
  remorse: {
    colorHex: "#947fc9",
    colorName: "Soft Lavender",
    emoji: "/images/remorse.jpeg",
    borderHex: "#4d5251",
    textHex: "#947fc9",
  },
  curiosity: {
    colorHex: "#947fc9",
    colorName: "Inquisitive Purple",
    emoji: "/images/curiosity.jpeg",
    borderHex: "#4d5251",
    textHex: "#947fc9",
  },
  joy: {
    colorHex: "#ccf060",
    colorName: "Sunny Yellow",
    emoji: "/images/joy.jpeg",
    borderHex: "#4d5251",
    textHex: "#ccf060",
  },
  caring: {
    colorHex: "#e49dfc",
    colorName: "Warm Pink",
    emoji: "/images/caring.jpeg",
    borderHex: "#4d5251",
    textHex: "#e49dfc",
  },
  embarrassment: {
    colorHex: "#9861ab",
    colorName: "Blushing Pink",
    emoji: "/images/embarrass.jpeg",
    borderHex: "#4d5251",
    textHex: "#9861ab",
  },
  optimism: {
    colorHex: "##e89b4f",
    colorName: "Bright Orange",
    emoji: "/images/optimism.jpeg",
    borderHex: "#4d5251",
    textHex: "#e89b4f",
  },
  fear: {
    colorHex: "#0b2c38",
    colorName: "Dark Indigo",
    emoji: "/images/fear.jpeg",
    borderHex: "#4d5251",
    textHex: "#2fb4cc",
  },
  relief: {
    colorHex: "#6fa66d",
    colorName: "Mint Green",
    emoji: "/images/relief.jpeg",
    borderHex: "#4d5251",
    textHex: "#6fa66d",
  },
  love: {
    colorHex: "#ff3333",
    colorName: "Romantic Red",
    emoji: "/images/love.jpeg",
    borderHex: "#4d5251",
    textHex: "#f75252",
  },
  anger: {
    colorHex: "#9c1a1a",
    colorName: "Fiery Red",
    emoji: "/images/angry.jpeg",
    borderHex: "#4d5251",
    textHex: "#f75757",
  },
  admiration: {
    colorHex: "#032f57",
    colorName: "Royal Blue",
    emoji: "/images/admire.jpeg",
    borderHex: "#4d5251",
    textHex: "#0777de",
  },
  desire: {
    colorHex: "#9c2d1c",
    colorName: "Passionate Red",
    emoji: "/images/desire.jpeg",
    borderHex: "#4d5251",
    textHex: "#ff5e66",
  },
  grief: {
    colorHex: "#280f4d",
    colorName: "Deep Purple",
    emoji: "/images/grief.jpeg",
    borderHex: "#4d5251",
    textHex: "#280f4d",
  },
  surprise: {
    colorHex: "#102f54",
    colorName: "Electric Blue",
    emoji: "/images/surprise.jpeg",
    borderHex: "#4d5251",
    textHex: "#3d63fc",
  },
  excitement: {
    colorHex: "#eff77e",
    colorName: "Energetic Yellow",
    emoji: "/images/excited.jpeg",
    borderHex: "#4d5251",
    textHex: "#eff77e",
  },
  disgust: {
    colorHex: "#2d9e29",
    colorName: "Sickly Green",
    emoji: "/images/disgust.jpeg",
    borderHex: "#4d5251",
    textHex: "#2d9e29",
  },
  gratitude: {
    colorHex: "#5fe1ed",
    colorName: "Thankful Turquoise",
    emoji: "/images/gratitudes.jpeg",
    borderHex: "#4d5251",
    textHex: "#5fe1ed",
  },
  amusement: {
    colorHex: "#ffa366",
    colorName: "Playful Orange",
    emoji: "/images/amused.jpeg",
    borderHex: "#4d5251",
    textHex: "#ffa366",
  },
  pride: {
    colorHex: "#824dff",
    colorName: "Bold Purple",
    emoji: "/images/proud.jpeg",
    borderHex: "#4d5251",
    textHex: "#824dff",
  },
};
